# Generated by Django 6.0.2 on 2026-05-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_add_published_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_color',
            field=models.CharField(blank=True, default='', help_text='CSS color code or name for the title', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='title_font_size',
            field=models.CharField(blank=True, default='', help_text='CSS font size for the title, e.g. 32px or 2rem', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='title_is_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='title_is_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Rich HTML content is allowed. Use paragraphs to structure your story.'),
        ),
    ]
