# Generated by Django 6.0.2 on 2026-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_title_color_post_title_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_position',
            field=models.CharField(blank=True, default='center center', help_text='CSS object-position for the cover image, e.g. "top center" or "50% 25%". Controls which part of the image is visible.', max_length=30),
        ),
    ]
