# Generated by Django 6.0.2 on 2026-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_cover_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default Font'), ("'Playfair Display', serif", 'Playfair Display (Elegant Serif)'), ("'Syne', sans-serif", 'Syne (Artistic / Modern)'), ("'Lato', sans-serif", 'Lato (Clean Body)'), ("'Inter', sans-serif", 'Inter (Contemporary Sans)'), ("'Outfit', sans-serif", 'Outfit (Premium Display)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Classic Luxury Serif)'), ("'Montserrat', sans-serif", 'Montserrat (Bold / Minimalist)')], default='', help_text='Select the font family for the body content', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default Font'), ("'Playfair Display', serif", 'Playfair Display (Elegant Serif)'), ("'Syne', sans-serif", 'Syne (Artistic / Modern)'), ("'Lato', sans-serif", 'Lato (Clean Body)'), ("'Inter', sans-serif", 'Inter (Contemporary Sans)'), ("'Outfit', sans-serif", 'Outfit (Premium Display)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Classic Luxury Serif)'), ("'Montserrat', sans-serif", 'Montserrat (Bold / Minimalist)')], default='', help_text='Select the font family for the excerpt', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='title_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default Font'), ("'Playfair Display', serif", 'Playfair Display (Elegant Serif)'), ("'Syne', sans-serif", 'Syne (Artistic / Modern)'), ("'Lato', sans-serif", 'Lato (Clean Body)'), ("'Inter', sans-serif", 'Inter (Contemporary Sans)'), ("'Outfit', sans-serif", 'Outfit (Premium Display)'), ("'Cormorant Garamond', serif", 'Cormorant Garamond (Classic Luxury Serif)'), ("'Montserrat', sans-serif", 'Montserrat (Bold / Minimalist)')], default='', help_text='Select the font family for the title', max_length=100),
        ),
    ]
