# Generated by Django 6.0.4 on 2026-05-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_user_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('min_delivery_days', models.PositiveSmallIntegerField(default=5)),
                ('max_delivery_days', models.PositiveSmallIntegerField(default=8)),
                ('region_digit', models.CharField(blank=True, help_text='Fallback when no prefix rule matches (India pincode first digit 1-9).', max_length=1)),
                ('is_default_region', models.BooleanField(default=False, help_text='Use as fallback for pincodes in this postal region.')),
                ('sort_order', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PincodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('prefix', 'Prefix'), ('exact', 'Exact pincode')], max_length=10)),
                ('value', models.CharField(db_index=True, max_length=6)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower number wins when multiple rules match.')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='orders.shippingzone')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'constraints': [models.UniqueConstraint(fields=('rule_type', 'value'), name='orders_pincode_rule_unique')],
            },
        ),
    ]
