# Generated by Django 6.0.2 on 2026-05-27 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingzone_pincoderule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^\\d{10}$')]),
        ),
    ]
