# Generated by Django 6.0.2 on 2026-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_contact_email_alter_order_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase_option',
            field=models.CharField(choices=[('individual', 'Individual'), ('set', 'Set')], default='individual', max_length=20),
        ),
    ]
