# Generated by Django 6.0.2 on 2026-06-22 14:37

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_purchase_option'),
        ('products', '0015_alter_product_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_type', models.CharField(choices=[('same', 'Same Item'), ('other', 'Another Item')], default='same', max_length=10)),
                ('reason', models.TextField(help_text='Customer-provided description of the issue (min 20 chars).')),
                ('unboxing_video', models.FileField(help_text='Continuous unedited unboxing video (MP4/MOV/WEBM, max 500 MB).', upload_to='exchange_videos/%Y/%m/')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending_review', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes explaining the approval or rejection decision.')),
                ('reference_id', models.CharField(db_index=True, default=orders.models._generate_reference_id, editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_product', models.ForeignKey(blank=True, help_text='Only set when exchange_type is "other".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_alternatives', to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='The specific item being exchanged (leave blank for whole-order exchanges).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='orders.orderitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending_review', 'approved', 'completed'])), fields=('order_item',), name='orders_exchange_one_active_per_item')],
            },
        ),
    ]
