# Generated by Django 6.0.4 on 2026-05-23 16:12

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_review_title'),
    ]

    def create_categories_and_copy(apps, schema_editor):
        Product = apps.get_model('products', 'Product')
        Category = apps.get_model('products', 'Category')
        # Create Category objects for existing distinct category names
        existing_names = Product.objects.values_list('category', flat=True).distinct()
        for name in existing_names:
            if not name:
                continue
            base = slugify(name)[:120]
            slug = base
            c = 1
            while Category.objects.filter(slug=slug).exists():
                slug = f"{base[:115]}-{c}"
                c += 1
            cat, _ = Category.objects.get_or_create(name=name, defaults={'slug': slug})
        # Map products to categories
        for p in Product.objects.all():
            if p.category:
                try:
                    cat = Category.objects.get(name=p.category)
                    p.category_obj = cat
                    p.save(update_fields=['category_obj'])
                except Category.DoesNotExist:
                    pass


    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='products_temp', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(create_categories_and_copy, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_obj',
            new_name='category',
        ),
    ]
