# Generated by Django 6.0.4 on 2026-05-23 16:12

from django.db import migrations


def populate_product_slugs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    from django.utils.text import slugify

    for p in Product.objects.filter(slug__isnull=True):
        base_slug = slugify(p.name)[:245]
        slug = base_slug
        counter = 1
        while Product.objects.filter(slug=slug).exclude(pk=p.pk).exists():
            slug = f"{base_slug[:240]}-{counter}"
            counter += 1
        p.slug = slug
        p.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_product_slug_alter_product_category'),
    ]

    operations = [
        migrations.RunPython(populate_product_slugs, reverse_code=migrations.RunPython.noop),
    ]
