# Generated by Django 6.0.2 on 2026-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_set_option',
            field=models.BooleanField(default=False, help_text='Allow buying as a set'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='set_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the set option', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
