# Generated by Django 6.0.2 on 2026-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_has_set_option_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2_position',
            field=models.CharField(blank=True, default='center center', help_text='CSS object-position for the second image, e.g. "top center" or "50% 25%".', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='image3_position',
            field=models.CharField(blank=True, default='center center', help_text='CSS object-position for the third image, e.g. "top center" or "50% 25%".', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='image_position',
            field=models.CharField(blank=True, default='center center', help_text='CSS object-position for the main image, e.g. "top center" or "50% 25%".', max_length=30),
        ),
    ]
