# Generated by Django 6.0.2 on 2026-05-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_image2_position_product_image3_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2_position',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3_position',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.CharField(blank=True, default='50% 50%', help_text='CSS object-position for the main image, e.g. "50% 50%". Use the visual picker grid above.', max_length=30),
        ),
    ]
