# Generated by Django 6.0.2 on 2026-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_image2_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_zoom',
            field=models.FloatField(default=1.0, help_text='CSS transform scale level for the collection page card, e.g. 1.0 to 3.0.'),
        ),
    ]
