# Generated by Django 6.0.4 on 2026-05-30 16:17

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, storage=products.models._video_storage, upload_to='products/videos/'),
        ),
    ]
