# Generated by Django 6.0.2 on 2026-05-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this guest cart should be cleaned up. NULL for user carts.', null=True),
        ),
    ]
