# Generated by Django 6.0.2 on 2026-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_add_expires_at_field'),
        ('products', '0010_product_has_set_option_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='purchase_option',
            field=models.CharField(choices=[('individual', 'Individual'), ('set', 'Set')], default='individual', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'purchase_option')},
        ),
    ]
