# Generated by Django 6.0.2 on 2026-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
