# Generated by Django 6.0.2 on 2026-05-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_add_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
