# Generated by Django 6.0.2 on 2026-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_add_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.CharField(choices=[('program', 'Professional Program'), ('experience', 'Studio Experience')], default='experience', help_text='Determines which grid section the workshop appears in on the studio page.', max_length=20),
        ),
        migrations.AddField(
            model_name='workshop',
            name='icon',
            field=models.CharField(blank=True, default='🏺', help_text='Single emoji displayed on the card and in the dropdown (e.g. 🌱, ✨, 🔥).', max_length=2),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='If true, the card gets the highlighted-card CSS class for extra visual emphasis.'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='schedule_text',
            field=models.CharField(blank=True, help_text='Human-friendly duration label shown on cards (e.g. "1 Month • 8 Classes", "2 Hours • For Two").', max_length=100),
        ),
    ]
